package vrcurso.framework.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class InternalFrame extends javax.swing.JInternalFrame {
    
    protected JFrame mainFrame;
    
    public void consultar() throws Exception {
    };
    
    public void novo() throws Exception {
    };
    
    public void remover() throws Exception {
    };
    
    public void salvar() throws Exception {
    };
    
    public void editar() throws Exception {
    };
    
    protected void limparTabela(JTable i_table){
        i_table.setModel(new DefaultTableModel());
    }

    /**
     * Creates new form ProfessorConsulta
     */
    public InternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        getContentPane().setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
