package vrcurso.framework.view;

import javax.swing.JFrame;

public class InternalFrame extends javax.swing.JInternalFrame {
    
    protected JFrame mainFrame;
    
    public void consultar() throws Exception {
    };
    
    public void novo() throws Exception {
    };
    
    public void remover() throws Exception {
    };
    
    public void salvar() throws Exception {
    };
    
    public void editar() throws Exception {
    };

    /**
     * Creates new form ProfessorConsulta
     */
    public InternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("VR Curso - Consulta de Professores");
        getContentPane().setLayout(null);

        setBounds(0, 0, 400, 300);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
